### ISSUE TITLE
Support other board sizes and partial boards

### ISSUE THREAD

**Issue by PJTraill** [hanysz/img2sgf#1]
The description of the algorithm suggests that it frequently uses the board size, suggesting that it will have problems with other sizes and partial diagrams. It would be nice to remove any such restrictions, perhaps allowing the user to give some tips.

**Comment by hanysz** [comment]
Sorry for the slow reply. Thanks for taking the time to comment!

Partial boards are implemented. I haven't tried, but I suspect if you try a small board then it will get interpreted as a corner position.  Larger boards will indeed fail completely.

Variable board sizes would be nice, but are not something I'd use myself, so I'm not going to spend time implementing them.  (I made this purely for personal use, and I'm not aware of a lot of other people using it.  I'd prefer to spend time on new projects rather than maintaining this one.)  If someone else implements such a feature, I'm happy to pull the changes into this repository.
